export type Product={id:number;name:string;slug:string;category:string;price:number;mrp:number;badge:string;type:"strip"|"neon"|"controller";stock:number;description:string;features:string[]};
export const PRODUCTS:Product[]=[
{id:1,name:"50M White LED Strip Light",slug:"50m-white-led-strip-light",category:"LED Strip Lights",price:1499,mrp:1999,badge:"BEST SELLER",type:"strip",stock:20,description:"Long-length white LED strip light for decorative and practical lighting.",features:["50 meter length","Single white colour","Flexible installation","Indoor decorative use"]},
{id:2,name:"45M White LED Strip Light",slug:"45m-white-led-strip-light",category:"LED Strip Lights",price:1399,mrp:1799,badge:"POPULAR",type:"strip",stock:18,description:"Bright and flexible white LED strip lighting for homes, shops and displays.",features:["45 meter length","Single white colour","Flexible design","Easy installation"]},
{id:3,name:"35M White LED Strip Light",slug:"35m-white-led-strip-light",category:"LED Strip Lights",price:1199,mrp:1599,badge:"VALUE",type:"strip",stock:25,description:"Value-focused long-length white LED strip light.",features:["35 meter length","Single white colour","Flexible installation","Indoor decorative use"]},
{id:4,name:"5M RGB-IC Neon Light",slug:"5m-rgb-ic-neon-light",category:"RGB-IC Neon Lights",price:999,mrp:1499,badge:"HOT",type:"neon",stock:30,description:"Dynamic RGB-IC neon light with flowing multi-colour effects.",features:["5 meter length","RGB-IC technology","Music sync","Remote/controller compatible","USB powered"]},
{id:5,name:"5M RGB-IC Smart Neon Light",slug:"5m-rgb-ic-smart-neon-light",category:"RGB-IC Neon Lights",price:1299,mrp:1799,badge:"NEW",type:"neon",stock:22,description:"Smart RGB-IC neon lighting with app, remote and dynamic effects.",features:["5 meter length","App control","Remote control","Music sync","Brightness adjustment"]},
{id:6,name:"RGB-IC Controller",slug:"rgb-ic-controller",category:"Accessories",price:299,mrp:499,badge:"",type:"controller",stock:40,description:"Controller accessory for compatible RGB-IC lighting products.",features:["Easy operation","Preset effects","Compact design"]},
{id:7,name:"LED Strip Light Controller",slug:"led-strip-light-controller",category:"Accessories",price:249,mrp:399,badge:"",type:"controller",stock:35,description:"Simple controller for compatible LED strip lights.",features:["Compact controller","Easy operation","Plug-and-use design"]},
{id:8,name:"RGB-IC Neon Light Combo",slug:"rgb-ic-neon-light-combo",category:"RGB-IC Neon Lights",price:1999,mrp:2799,badge:"COMBO",type:"neon",stock:12,description:"Bundle of RGB-IC neon lighting for larger decorative setups.",features:["Multi-colour effects","Dynamic modes","Great for parties and rooms"]}];
