name="great-american-store-api"
main="src/index.ts"
compatibility_date="2026-08-01"
[[d1_databases]]
binding="DB"
database_name="great-american-store"
database_id="7403e1e8-756d-48d1-9b51-755ea0b8d3e6" 
